### ISSUE TITLE
HELP!!!!!

### ISSUE THREAD

**Issue by nuonuo1919** [ValentinFunk/Pointshop2#156]
I have a question. Why is there no icon in my pointshop?
![QQ图片20210221114634](https://user-images.githubusercontent.com/54161947/108614971-74b6e300-743a-11eb-94cb-f66ef48625d1.png)

**Comment by Dimantio** [comment]
Update your ps2, I resolved this issue a little while ago!

**Comment by Niko1331** [comment]
> Update your ps2, I resolved this issue a little while ago!

Hi, my version is the latest version but there is still no icon

**Comment by Dimantio** [comment]
Use the regenerate icons in your client settings

**Comment by Niko1331** [comment]
> Use the regenerate icons in your client settings

He only loaded the model
